# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageDelivery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageDelivery.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15MessageDelivery.proto\"A\n\rclientrequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x16\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x06.event\"5\n\x05\x65vent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x05\"1\n\x04recv\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x05\x32\x38\n\x0bMsgDelivery\x12)\n\x0e\x63lient_request\x12\x0e.clientrequest\x1a\x05.recv\"\x00\x62\x06proto3')
)




_CLIENTREQUEST = _descriptor.Descriptor(
  name='clientrequest',
  full_name='clientrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='clientrequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='clientrequest.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='clientrequest.events', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=90,
)


_EVENT = _descriptor.Descriptor(
  name='event',
  full_name='event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='event.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interface', full_name='event.interface', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='money', full_name='event.money', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=145,
)


_RECV = _descriptor.Descriptor(
  name='recv',
  full_name='recv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='recv.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='recv.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='recv.balance', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=196,
)

_CLIENTREQUEST.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['clientrequest'] = _CLIENTREQUEST
DESCRIPTOR.message_types_by_name['event'] = _EVENT
DESCRIPTOR.message_types_by_name['recv'] = _RECV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

clientrequest = _reflection.GeneratedProtocolMessageType('clientrequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTREQUEST,
  __module__ = 'MessageDelivery_pb2'
  # @@protoc_insertion_point(class_scope:clientrequest)
  ))
_sym_db.RegisterMessage(clientrequest)

event = _reflection.GeneratedProtocolMessageType('event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'MessageDelivery_pb2'
  # @@protoc_insertion_point(class_scope:event)
  ))
_sym_db.RegisterMessage(event)

recv = _reflection.GeneratedProtocolMessageType('recv', (_message.Message,), dict(
  DESCRIPTOR = _RECV,
  __module__ = 'MessageDelivery_pb2'
  # @@protoc_insertion_point(class_scope:recv)
  ))
_sym_db.RegisterMessage(recv)



_MSGDELIVERY = _descriptor.ServiceDescriptor(
  name='MsgDelivery',
  full_name='MsgDelivery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=198,
  serialized_end=254,
  methods=[
  _descriptor.MethodDescriptor(
    name='client_request',
    full_name='MsgDelivery.client_request',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUEST,
    output_type=_RECV,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSGDELIVERY)

DESCRIPTOR.services_by_name['MsgDelivery'] = _MSGDELIVERY

# @@protoc_insertion_point(module_scope)
