# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import MessageDelivery_pb2 as MessageDelivery__pb2


class MsgDeliveryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.client_request = channel.unary_unary(
        '/MsgDelivery/client_request',
        request_serializer=MessageDelivery__pb2.clientrequest.SerializeToString,
        response_deserializer=MessageDelivery__pb2.recv.FromString,
        )


class MsgDeliveryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def client_request(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MsgDeliveryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'client_request': grpc.unary_unary_rpc_method_handler(
          servicer.client_request,
          request_deserializer=MessageDelivery__pb2.clientrequest.FromString,
          response_serializer=MessageDelivery__pb2.recv.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MsgDelivery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
